NextTeamB/ONEHOUR

- .github/ISSUE_TEMPLATE/✨feature.md
- .github/ISSUE_TEMPLATE/🐞-bug.md
- .github/ISSUE_TEMPLATE/📄-etc.md
이슈 템플릿 세분화 및 작성
Related to : #2
> feature/#2-이슈 템플릿 생성

- app/layout.tsx
- app/page.tsx
- app/provider.tsx
- app/sign-in/page.tsx
- app/sign-in/signIn.module.scss
- package-lock.json
- package.json
- slices/userSlice.ts
- store/store.ts
#15 회원가입 페이지 퍼블리싱 작업 및 디자인 적용
- ui적 로직은 아직 미적용상태이며 추후 로그인 기능 구현 완료 전까지 bugfix 예정
- 체크박스 로직 역시 마찬가지로 추후 개선 예정
- Redux 도입 완료 (파일 및 디렉토리 포함)
- Redux-persist 는 금일 8/1일 회의 후 논의 (버전이슈)
> #15 design: 회원가입 페이지 제작

- app/page.tsx
- app/sign-in/page.tsx
- app/sign-in/signIn.module.scss
- package-lock.json
- package.json
- pages/api/getData.ts
Axios 도입 및 더미데이터 테스트
- Axios 적용하여 로컬 데이터 파일 GET 요청 및 POST 요청 테스팅
GET / POST 무한요청 오류사항 해결 완료
추가사항 : email 중복확인 버튼 UI 추가 완료 (/sign-in)
- DELETE / PUT / PATCH 테스트는 언제 수행할까요??
> #25 feat: Axios 도입 및 더미데이터 테스트

- app/provider.tsx
- package-lock.json
- package.json
- store/store.ts
- yarn.lock
- redux-persist 적용해 새로고침 시에도 정보 유지
- 이후 서버에서 받아온 유저 정보 저장하는 slice 작성하여 반영하면 될 것 같습니다!
> #19 feat: redux-persist 라이브러리 적용

- app/dashboard/challenges/new-challenge/page.tsx
- app/dashboard/challenges/ongoing-challenge/animation.tsx
- app/dashboard/challenges/ongoing-challenge/page.tsx
- app/dashboard/page.tsx
- app/page.tsx
- slices/challengeSlice.ts
- store/store.ts
-  jotai로 챌린지 정보 저장하는 로직을 redux slice로 대체
- challenge 기록 요청 추가
-
> #43 feat: jotai로 챌린지 정보 저장 로직 redux slice로 대체

- app/dashboard/challengers/challengers.module.scss
- app/dashboard/challengers/page.tsx
- app/info/info.module.css
scss 수정사항 반영
-  scss 수정 작업 완료
- 없습니다
> #63 design: scss 수정사항 반영

- app/dashboard/challenges/ongoing-challenge/page.tsx
- app/dashboard/page.tsx
- app/info/page.tsx
- 로티 파일 컴포넌트 선언 방식 수정 export function -> function
-
> #70 bugfix: 배포 중 에러 해결

- app/dashboard/challenges/ongoing-challenge/page.tsx
- app/dashboard/page.tsx
- app/info/page.tsx
> Revert "#70 bugfix: 배포 중 에러 해결"

- app/page.tsx
- app/page.tsx LayoutProps 타입 에러 NextPage로 수정
-
> #70 bugfix: 배포 오류 수정(1)

- components/loginButton.tsx
- componets/loginButton.tsx 삭제
-
> #70 bugfix: 배포 오류 수정(3)

- app/sign-up/page.tsx
> #75 feat: signup 아이디 중복 체크

- app/dashboard/time-ranking/page.tsx
- pages/api/rank.js
랭킹 API 구현 및 차트컴포넌트 데이터 통합
- 랭킹 API 구현 및 DB 상 totalChallenge 필드 생성
- 차트 컴포넌트 데이터 통합
- 다음 이슈에서 Redux 제거 진행하겠습니다
> #80 feat: 랭킹 API 구현 및 차트컴포넌트 데이터 통합

- app/dashboard/image-upload/page.tsx
- app/login/page.tsx
- package-lock.json
- package.json
- pages/api/image.js
- util/onImageUpload.js
- aws S3 버킷 생성 및 연결
- presigned Url을 생성하고 이미지 업로드하는 기능 구현
-
> #102 feat: aws S3 버킷에 이미지 업로드하는 기능 구현

- app/dashboard/challenges/ongoing-challenge/ongoing-challenge.module.scss
- app/dashboard/challenges/ongoing-challenge/page.tsx
- app/dashboard/records/page.tsx
- package-lock.json
- package.json
- pages/api/records.js
- util/onContinuerBoard.js
- util/postChallengeData.js
Records 페이지 기능 보수작업
- Challenge API [POST] 기록 date 값 Type 변경
- 최근 30일 기준 기록 카운트 로직 구현 
-
> #124 feat : Records 페이지 기능 보수작업

- app/dashboard/challengers/[postId]/page.tsx
- app/dashboard/challengers/[postId]/postId.module.scss
- app/dashboard/challengers/challengers.module.scss
- app/dashboard/challengers/new-post/page.tsx
- app/dashboard/settings/page.tsx
- app/dashboard/settings/settings.module.scss
- app/dashboard/time-ranking/page.tsx
- next.config.js
- pages/api/challengers.js
- pages/api/image-upload.js
- pages/api/users/image.js
Challengers 페이지 보수작업
- Settings API 보수 및 프로필 이미지 변경 기능 보수
- Challengers 페이지 전 기능 보수
- Redux 프로필 이미지 URL 마운트 -> Settings 페이지
- Axios 중복 요청 방지 처리
- 로그인 Validation Check
> #128 feat : Challengers 페이지 보수작업

- app/dashboard/challengers/[postId]/page.tsx
- app/dashboard/challengers/new-post/new-post.module.scss
- app/dashboard/challengers/new-post/page.tsx
- app/dashboard/challengers/page.tsx
- pages/api/users/account.js
보수사항 및 기능점검
- Settings 유저정보 GET API 수정
- Axios 중복 요청 방지 처리
- 남은 사항 새 이슈에서 작업예정
> #132 fix : 보수사항 및 기능점검

- app/dashboard/time-ranking/ranking.module.scss
Rank page SCSS
- Rank page SCSS
-
> #141 design : Rank page SCSS

- app/dashboard/settings/page.tsx
- app/dashboard/time-ranking/page.tsx
- app/login/page.tsx
- pages/api/users/image.js
Environment Variable Check
- Environment Variable Change
-
> #142 fix : Environment Variable Check

- components/navigator/Navigator.tsx
- pages/api/auth/login.js
- util/onSignUp.js
- 내비게이션 바 디자인 변경사항 적용
- 로그인 api GET 요청 메소드 삭제
- 회원가입 시 비밀번호 해시 및 프로퍼티 삭제
-
> #103 feat: 내비게이션 바 디자인 변경사항 적용

- app/dashboard/challenges/challenges.module.scss
- app/dashboard/challenges/new-challenge/new-challenge.module.scss
- app/dashboard/challenges/ongoing-challenge/ongoing-challenge.module.scss
- app/globals.css
> #144 feat: 웹폰트 수정

- components/navigator/Navigator.module.scss
- components/navigator/Navigator.tsx
- public/_utils.scss
- 내비게이션 바 CSS 단위 반응형으로 수정
- 회원가입 시 비밀번호 해시 및 프로퍼티 삭제
- 로그인 api GET 요청 메소드 삭제
-
> #103 design: 내비게이션 바 CSS 단위 반응형으로 수정

- app/dashboard/settings/settings.module.scss
- app/dashboard/time-ranking/page.tsx
- app/dashboard/time-ranking/ranking.module.scss
- pages/api/records.js
Settings 페이지 반응형 구현
- Settings 페이지 반응형 구현
- rank / challenge API 수정
-
> #154 design: Settings 페이지 반응형 구현

- app/dashboard/settings/page.tsx
- pages/api/users/withdrawal.js
> #158 feat: 회원탈퇴 기능 수정
